@extends('frontend._layouts.master')

@section('content')
    <main class="flex-grow-1">
        <article class="container py-40 py-lg-5 py-xxl-80">
            <div class="row justify-content-center">
                <div class="col-xl-10 col-xxl-8">
                    <h1 class="mb-3 mb-lg-40">
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">Tax Biz Legal Services Privacy Policy</font>
                        </font>
                    </h1>

                    <h2>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">1. GENERAL</font>
                        </font>
                    </h2>
                    <p>
                        {{-- <strong>
                            <font style="vertical-align: inherit;">
                                <font style="vertical-align: inherit;">1.1. Document content.</font>
                            </font>
                        </strong> --}}
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">1.1 This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">1.2 This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of taxbizlegal.com</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">1.3 The domain name legalbharatservices.com ("Website"), is owned and operated by LBS LEGAL WORKS PRIVATE LIMITED and having its&nbsp;office at 3RD-FR FL-2, 19/C, Ibrahim Road, Kolkata, Kolkata, West Bengal, 700023, where such expression shall, unless repugnant to the context thereof, be deemed to include its respective representatives, administrators, employees.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">1.4  For the purpose of this Privacy Policy (“Policy”), wherever the context so requires,</font>
                        </font>
                    </p>
                    <div class="ps-3">
                        <p><strong>
                                <font style="vertical-align: inherit;">
                                    <font style="vertical-align: inherit;">a)</font>
                                </font>
                            </strong>
                            <font style="vertical-align: inherit;">
                                <font style="vertical-align: inherit;"> The term ‘You’ &amp;‘User’ shall mean any legal person or entity accessing or using the services provided on this Website, who is competent to enter into binding contracts, as per the provisions of the Indian Contract Act, 1872;
                                </font>
                            </font>
                        </p>
                        <p><strong>
                                <font style="vertical-align: inherit;">
                                    <font style="vertical-align: inherit;">b)</font>
                                </font>
                            </strong>
                            <font style="vertical-align: inherit;">
                                <font style="vertical-align: inherit;">  The terms ‘We’, ‘Us’&amp; ‘Our’ shall mean the Website, as the context so requires./font>
                            </font>
                        </p>
                        <p><strong>
                                <font style="vertical-align: inherit;">
                                    <font style="vertical-align: inherit;">c)</font>
                                </font>
                            </strong>
                            <font style="vertical-align: inherit;">
                                <font style="vertical-align: inherit;">The terms ‘Party’ &amp; ‘Parties’ shall respectively be used to refer to the User and the website individually and collectively, as the context so requires.</font>
                            </font>
                        </p>
                    </div>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">1.5 The headings of each section in this Policy are only for the purpose of organizing the various provisions under this Policy in an orderly manner, and shall not be used by either Party to interpret the provisions contained herein in any manner. Further, it is specifically agreed to by the Parties that the headings shall have no legal or contractual value.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">1.6 The use of the Website by the User is solely governed by this Policy as well as the Terms of Use of the Website (“Terms”, available at www. legalbharatservices), and any modifications or amendments made thereto by the Website&nbsp;from time to time, at its sole discretion. Visiting the home page of the Website and/or using any of the services provided on the Website shall be deemed to signify the User’s unequivocal acceptance of this Policy and the aforementioned Terms, and the User expressly agrees to be bound by the same. The User expressly agrees and acknowledges that the Terms and Policy are co-terminus, and that expiry/termination of either one will lead to the termination of the other.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">1.7 The User unequivocally agrees that this Policy and the aforementioned Terms constitute a legally binding agreement between the User and the Website, and that the User shall be subject to the rules, guidelines, policies, terms, and conditions applicable to any service that is provided by the Website, and that the same shall be deemed&nbsp;into the Terms, and shall be treated as part and parcel of the same. The User acknowledges and agrees that no signature or express act is required to make these Terms and the Policy binding on the User and that the User’s act of visiting any part of the Website constitutes the User’s full and final acceptance of the Policy and the aforementioned Terms.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">1.8 The Parties expressly agree that the Website retains the sole and exclusive right to amend or modify the Policy and the aforementioned Terms without any prior permission or intimation to the User, and the User expressly agrees that any such amendments or modifications shall come into effect immediately. The User has a duty to periodically check the Policy and Terms, and stay updated on their provisions and requirements. If the User continues to use the Website following such a change, the User will be deemed to have consented to any and all amendments/modifications made to the Policy and Terms. In so far as the User complies with the Policy and Terms, he/she is granted a personal, non-exclusive, non-transferable, revocable, limited privilege to enter, access, and use the Website.</font>
                        </font>
                    </p>
                    <br>
                    <h2>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">2. COLLECTION OF PERSONAL AND OTHER INFORMATION</font>
                        </font>
                    </h2>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">2.1 The User expressly agrees and acknowledges that the Website collects and stores the user's personal information, which is provided by the User from time to time on the Website, including but not limited to the User’s user name, passwords, email address, name, address, age, date of birth, sex, nationality, shopping preferences, browsing history, etc., as well as any images or other information uploaded/published by the User on the Website. The User is aware that this information will be used by the Website to provide services and features targeted at the User, that are most likely to meet the User’s needs, and also to customize and improve the Website to make its users’ experiences safer and easier.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">2.2 The User is aware that the Website may automatically track certain information about the User based upon the User’s IP address and the User’s behavior on the Website, and the User expressly consents to the same. The User is aware that this information is used to do internal research on user demographics, interests, and behavior, to enable the Website to better understand, and cater to the interests of its users. The User is expressly made aware that such information may include the URL that the User visited prior to accessing the Website, the URL which the User subsequently visits (whether or not these URLs form a part of the Website), the User’s computer &amp; web browser information, the User’s IP address, etc.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">2.3 If the User chooses to purchase products/services from the Website, the User consents to allow the Website to collect information about the User’s buying behavior and trends.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">2.4 If the User chooses to post messages/reviews/feedback anywhere on the Website, including but not limited to message boards, chat rooms, other message areas, etc., the User is aware that any and all such information provided/uploaded will be collected and stored by the Website indefinitely, and that such retained information may be used to resolve disputes, provide customer support, troubleshoot problems.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">2.5 The User is aware that while he/she can browse some sections of the Website without being a registered user, certain activities (such as placing an order) require the User to provide valid personal information to the Website for the purpose of registration. The User is aware that the contact information provided to the Website may be used to send the User offers and promotions, whether or not based on the user's previous orders and interests, and the User hereby expressly consents to receive the same.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">2.6 The User is aware that the Website may occasionally request the User to complete optional online surveys. These surveys may require the User to provide contact information and demographic information (like zip code, age, income bracket, sex, etc.). The User is aware that this data is used to customize the Website for the benefit of the User, and to provide all users of the Website with products/services/content that the Website believes they might be interested in availing of, and also to display content according to the User’s preferences.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">2.7 The User is further aware that the Website may occasionally request the User to write reviews for products/services purchased/availed of the User from the Website, and also reviews for the various sellers listing their products/services on the website. The User is aware that such reviews will help other users of the website make prudent and correct purchases, and also help the Website remove sellers whose products are unsatisfactory in any way, and the User hereby expressly authorizes the Website to publish any and all reviews written by the User on the Website, along with the User’s name and certain contact details, for the benefit and use of other Users of the Website.</font>
                        </font>
                    </p>
                    <br>
                    <h2>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">3.COOKIES</font>
                        </font>
                    </h2>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">3.1 The User is aware that a cookie is a small piece of information stored by a web server on a web browser so it can later be traced back from that particular browser, and that cookies are useful for enabling the browser to remember information specific to a given user, including but not limited to a User’s login identification, password, etc. The User is aware that the Website places both permanent and temporary cookies in the User’s computer's hard drive and web browser, and does hereby expressly consent to the same.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">3.2 The User is further aware that the Website uses data collection devices such as cookies on certain pages of the Website to help analyze web page flow, measure promotional effectiveness, and promote trust and safety, and that certain features of the Website are only available through the use of such cookies. While the User is free to decline the Website’s cookies if the User’s browser permits, the User may consequently be unable to use certain features on the Website.
                            </font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">3.3 Additionally, the User is aware that he/she might encounter ‘cookies’ or other similar devices on certain pages of the Website that are placed by third parties or affiliates of the Website. The User expressly agrees and acknowledges that the Website does not control the use of such cookies/other devices by third parties, that the Website is in no way responsible for the same, and that the User assumes any and all risks in this regard.
                            </font>
                        </font>
                    </p>
                    <br>
                    <h2>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">4. SHARING OF PERSONAL INFORMATION</font>
                        </font>
                    </h2>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">4.1  The User is aware that the Website may share the User’s personal information with other corporate entities and affiliates to help detect and prevent identity theft, fraud and other potentially illegal acts; correlate related or multiple accounts to prevent abuse of the Website’s services; and to facilitate joint or co-branded services, where such services are provided by more than one corporate entity.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">4.2 The User is aware that the Website may disclose personal information if required to do so by law or if the Website in good faith believes that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal processes. The Website may also disclose the User’s personal information to law enforcement offices, third party rights owners, or other third parties if it believes that such disclosure is reasonably necessary to enforce the Terms or Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of its users, or the general public.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">4.3 The User is further aware that the Website and its affiliates may share/sell some or all of the User’s personal information with other business entities should the Website (or its assets) plan to merge with, or be acquired by such business entity, or in the event of re-organization, amalgamation, or restructuring of the Website’s business. Such business entity or new entity will continue to be bound by the Terms and Policy, as may be amended from time to time.
                            </font>
                        </font>
                    </p>
                    <br>
                    <h2>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">5. SECURITY</font>
                        </font>
                    </h2>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">5.1 Transactions on the Website are secure and protected. Any information entered by the User when transacting on the Website is encrypted to protect the User against unintentional disclosure to third parties. The User’s credit and debit card information is not received, stored by, or retained by the Website in any manner. This information is supplied by the User directly to the relevant payment gateway which is authorized to handle the information provided and is compliant with the regulations and requirements of various banks and institutions and payment franchisees that it is associated with.</font>
                        </font>
                    </p>
                    <br>
                    <h2>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">6. USER’S CONSENT</font>
                        </font>
                    </h2>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">6.1 By using the Website and/ or by providing information to the Website through the Website, the User consents to the collection and use of the information disclosed by the User on the Website in accordance with this Policy, including but not limited to the User’s consent the Website sharing/divulging the User’s information, as per the terms contained hereinabove in Section 4 of the Policy.</font>
                        </font>
                    </p>
                    <br>
                    <h2>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">7. DISPUTE RESOLUTION AND JURISDICTION</font>
                        </font>
                    </h2>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">7.1 In case of any dispute between the parties, the Parties will attempt to resolve the same amicably amongst themselves, to the mutual satisfaction of both Parties. In the event that the Parties are unable to reach such an amicable solution within thirty (30) days of one Party communicating the existence of a dispute to the other Party, the dispute will be resolved by arbitration.</font>
                        </font>
                    </p>
                    <p>
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">7.2 The Parties expressly agree that the Terms, Policy, and any other agreements entered into between the Parties are governed by the laws, rules, and regulations of India, and that the Courts at Kolkata, West Bengal, shall have exclusive jurisdiction over any disputes arising between the Parties.</font>
                        </font>
                    </p>
                </div>
            </div>
        </article>
    </main>
@endsection
