<?php

return [
    "private-limited-company" => [
        [
            "plan_name" => "Basic",
            "price" => 3999,
            "description" => "Essential features to kickstart<br> your business effortlessly.",
            "is_popular" => false,
            "services" => [
                ["name" => "Company Registration", "is_active" => 2],
                ["name" => "Drafting & Filing by CA/CS", "is_active" => 1],
                ["name" => "MCA Processing & CIN", "is_active" => 1],
                ["name" => "Company PAN & TAN", "is_active" => 1],
                ["name" => "MOA & AOA", "is_active" => 1],
                ["name" => "Allotment of 2 DINs", "is_active" => 1],
                ["name" => "Share Certificate", "is_active" => 1],
                ["name" => "ESI & PF Registration", "is_active" => 1],
                ["name" => "GST Registration", "is_active" => 0],
                ["name" => "ADT-1", "is_active" => 0],
                ["name" => "INC-20A (Commencement of Business)", "is_active" => 0],
                ["name" => "MGT-7", "is_active" => 0],
                ["name" => "AOC-4", "is_active" => 0],
                ["name" => "DIR 3 KYC", "is_active" => 0],
                ["name" => "First Board Resolution", "is_active" => 0],
                ["name" => "Trademark Registration", "is_active" => 0],
                ["name" => "GST Return Filing 3 Months", "is_active" => 0],
                ["name" => "Income Tax Filings", "is_active" => 0],
            ]
        ],
        [
            "plan_name" => "Standard",
            "price" => 6999,
            "description" => "Enhanced services <br>for smooth business operations.",
            "is_popular" => true,
            "services" => [
                ["name" => "Company Registration", "is_active" => 2],
                ["name" => "Drafting & Filing by CA/CS", "is_active" => 1],
                ["name" => "MCA Processing & CIN", "is_active" => 1],
                ["name" => "Company PAN & TAN", "is_active" => 1],
                ["name" => "MOA & AOA", "is_active" => 1],
                ["name" => "Allotment of 2 DINs", "is_active" => 1],
                ["name" => "Share Certificate", "is_active" => 1],
                ["name" => "ESI & PF Registration", "is_active" => 1],
                ["name" => "GST Registration", "is_active" => 1],
                ["name" => "ADT-1", "is_active" => 1],
                ["name" => "INC-20A (Commencement of Business)", "is_active" => 1],
                ["name" => "MGT-7", "is_active" => 0],
                ["name" => "AOC-4", "is_active" => 0],
                ["name" => "DIR 3 KYC", "is_active" => 0],
                ["name" => "First Board Resolution", "is_active" => 0],
                ["name" => "Trademark Registration", "is_active" => 0],
                ["name" => "GST Return Filing 3 Months", "is_active" => 0],
                ["name" => "Income Tax Filings", "is_active" => 0],
            ]
        ],
        [
            "plan_name" => "Premium",
            "price" => 19999,
            "description" => "Comprehensive solutions<br> for business growth and success.",
            "is_popular" => false,
            "services" => [
                ["name" => "Company Registration", "is_active" => 2],
                ["name" => "Drafting & Filing by CA/CS", "is_active" => 1],
                ["name" => "MCA Processing & CIN", "is_active" => 1],
                ["name" => "Company PAN & TAN", "is_active" => 1],
                ["name" => "MOA & AOA", "is_active" => 1],
                ["name" => "Allotment of 2 DINs", "is_active" => 1],
                ["name" => "Share Certificate", "is_active" => 1],
                ["name" => "ESI & PF Registration", "is_active" => 1],
                ["name" => "GST Registration", "is_active" => 1],
                ["name" => "ADT-1", "is_active" => 1],
                ["name" => "INC-20A (Commencement of Business)", "is_active" => 1],
                ["name" => "MGT-7", "is_active" => 1],
                ["name" => "AOC-4", "is_active" => 1],
                ["name" => "DIR 3 KYC", "is_active" => 1],
                ["name" => "First Board Resolution", "is_active" => 1],
                ["name" => "Trademark Registration", "is_active" => 1],
                ["name" => "GST Return Filing 3 Months", "is_active" => 1],
                ["name" => "Income Tax Filings", "is_active" => 1],
            ]
        ]
    ],
    "one-person-company" => [
        [
            "plan_name" => "Basic",
            "price" => 4999,
            "description" => "Essential features to kickstart<br> your business effortlessly.",
            "is_popular" => false,
            "services" => [
                ["name" => "DSC", "is_active" => 1],
                ["name" => "Allotment of DIN", "is_active" => 1],
                ["name" => "Name approval through Form SPICe+", "is_active" => 1],
                ["name" => "Copy of e-MOA & e-AOA", "is_active" => 1],
                ["name" => "Allotment of EPAN through Form SPICe+", "is_active" => 1],
                ["name" => "Allotment of ETAN through Form SPICe+", "is_active" => 1],
                ["name" => "PF registration through Form SPICe+", "is_active" => 1],
                ["name" => "ESI registration through Form SPICe+", "is_active" => 1],
                ["name" => "Bank account opening in nearest branch", "is_active" => 1],
                ["name" => "Share certificate", "is_active" => 1],
                ["name" => "GST registration", "is_active" => 0],
                ["name" => "ADT-1", "is_active" => 0],
                ["name" => "Form INC 20A<br>(Commencement of Business)", "is_active" => 0],
                ["name" => "TMR", "is_active" => 0],
                ["name" => "Company seal", "is_active" => 0],
                ["name" => "ITR filing for 1st year", "is_active" => 0],
                ["name" => "Auditor appointment", "is_active" => 0],
                ["name" => "MGT-7 filing", "is_active" => 0],
                ["name" => "AOC-4 filing", "is_active" => 0],
                ["name" => "DIN KYC of director", "is_active" => 0],
                ["name" => "GST return filing for 6 months<br>(2 directors)", "is_active" => 0]
            ]
        ],
        [
            "plan_name" => "Standard",
            "price" => 8999,
            "description" => "Enhanced services <br>for smooth business operations.",
            "is_popular" => true,
            "services" => [
                ["name" => "DSC", "is_active" => 1],
                ["name" => "Allotment of DIN", "is_active" => 1],
                ["name" => "Name approval through Form SPICe+", "is_active" => 1],
                ["name" => "Copy of e-MOA & e-AOA", "is_active" => 1],
                ["name" => "Allotment of EPAN through Form SPICe+", "is_active" => 1],
                ["name" => "Allotment of ETAN through Form SPICe+", "is_active" => 1],
                ["name" => "PF registration through Form SPICe+", "is_active" => 1],
                ["name" => "ESI registration through Form SPICe+", "is_active" => 1],
                ["name" => "Bank account opening in nearest branch", "is_active" => 1],
                ["name" => "Share certificate", "is_active" => 1],
                ["name" => "GST registration", "is_active" => 1],
                ["name" => "ADT-1", "is_active" => 1],
                ["name" => "Form INC 20A<br>(Commencement of Business)", "is_active" => 0],
                ["name" => "TMR", "is_active" => 0],
                ["name" => "Company seal", "is_active" => 0],
                ["name" => "ITR filing for 1st year", "is_active" => 0],
                ["name" => "Auditor appointment", "is_active" => 0],
                ["name" => "MGT-7 filing", "is_active" => 0],
                ["name" => "AOC-4 filing", "is_active" => 0],
                ["name" => "DIN KYC of director", "is_active" => 0],
                ["name" => "GST return filing for 6 months<br>(2 directors)", "is_active" => 0]
            ]
        ],
        [
            "plan_name" => "Premium",
            "price" => 17999,
            "description" => "Comprehensive solutions<br> for business growth and success.",
            "is_popular" => false,
            "services" => [
                ["name" => "DSC", "is_active" => 1],
                ["name" => "Allotment of DIN", "is_active" => 1],
                ["name" => "Name approval through Form SPICe+", "is_active" => 1],
                ["name" => "Copy of e-MOA & e-AOA", "is_active" => 1],
                ["name" => "Allotment of EPAN through Form SPICe+", "is_active" => 1],
                ["name" => "Allotment of ETAN through Form SPICe+", "is_active" => 1],
                ["name" => "PF registration through Form SPICe+", "is_active" => 1],
                ["name" => "ESI registration through Form SPICe+", "is_active" => 1],
                ["name" => "Bank account opening in nearest branch", "is_active" => 1],
                ["name" => "Share certificate", "is_active" => 1],
                ["name" => "GST registration", "is_active" => 1],
                ["name" => "ADT-1", "is_active" => 1],
                ["name" => "Form INC 20A<br>(Commencement of Business)", "is_active" => 1],
                ["name" => "TMR", "is_active" => 1],
                ["name" => "Company seal", "is_active" => 1],
                ["name" => "ITR filing for 1st year", "is_active" => 1],
                ["name" => "Auditor appointment", "is_active" => 1],
                ["name" => "MGT-7 filing", "is_active" => 1],
                ["name" => "AOC-4 filing", "is_active" => 1],
                ["name" => "DIN KYC of director", "is_active" => 1],
                ["name" => "GST return filing for 6 months<br>(2 directors)", "is_active" => 1]
            ]
        ]
    ]
];
